name: Deploy static Next.js to GitHub Pages

on:
  push:
    branches: [ pages ]
  workflow_dispatch:

# Allow one concurrent deployment
concurrency:
  group: pages-deployment
  cancel-in-progress: true

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: frontend/package.json

      - name: Install dependencies
        run: npm ci

      - name: Build and Export
        env:
          GITHUB_ACTIONS: 'true'
        run: |
          npm run build
          # next build with output: 'export' writes static HTML to out/
          # run post-export script to create 404.html
          npm run postexport || true

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
            path: frontend/out

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
